### ISSUE TITLE
This does not work at all.  Missing "DeletionPolicy: Retain" for starters

### ISSUE THREAD

**Issue by dustball** [aws-solutions/edit-in-the-cloud-on-aws#2]
I wasted 12 hours of critical prep time for a new job; I'm now super stressed and I wish I never heard of this approach.  

Even adding `DeletionPolicy: Retain`, it still breaks.

**Comment by mhersonaws** [comment]
What error did you get in cloudformation?  Can you post the output?

**Comment by mhersonaws** [comment]
Resolved with v2.0
